//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leap.BookStore.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Items
    {
        public System.Guid order_Item_ID { get; set; }
        public System.Guid order_ID { get; set; }
        public System.Guid book_ID { get; set; }
        public string Item_Number { get; set; }
        public decimal Item_Agreed_Price { get; set; }
        public string Item_comment { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Order Order { get; set; }
    }
}
